import React, {type CSSProperties, type ReactNode} from "react";
import {AbsoluteFill, Audio, Easing, Sequence, interpolate, useCurrentFrame, useVideoConfig} from "remotion";
import {fonts} from "../../fonts";
import {getSfxUrl} from "../../sfx/synth";
import {LucideIcon, type LucideIconName} from "./LucideIcon";

export enum AppleMotionVariant {
  DarkStage = "dark-stage", LightStage = "light-stage", GlassButton = "glass-button", Toggle = "toggle",
  SegmentControl = "segment-control", Metric = "metric", LineChart = "line-chart", Comparison = "comparison",
  DataFlow = "data-flow", Table = "table", ScreenWindow = "screen-window", PresenterGraphic = "presenter-graphic",
  BigStatement = "big-statement", ProcessNetwork = "process-network", SummarySteps = "summary-steps",
}

export interface AppleMotionItem {label: string; value?: string | number; detail?: string; color?: string}
export interface AppleMotionProps {
  variant: AppleMotionVariant; title?: string; subtitle?: string; primary?: string; background?: string;
  value?: string | number; secondaryValue?: string | number; labels?: string[];
  items?: Array<AppleMotionItem | string>; audioEnabled?: boolean;
}

const DARK = "#050506";
const LIGHT = "#f5f5f7";
const BLUE = "#2997ff";
const GREEN = "#30d158";
const PINK = "#ff375f";
const ORANGE = "#ff9f0a";
const appleEase = Easing.bezier(0.22, 1, 0.36, 1);
const clamp = {extrapolateLeft: "clamp", extrapolateRight: "clamp"} as const;
const glass: CSSProperties = {background: "linear-gradient(145deg,rgba(255,255,255,.18),rgba(255,255,255,.055))", border: "1px solid rgba(255,255,255,.2)", boxShadow: "0 34px 90px rgba(0,0,0,.3),inset 0 1px 0 rgba(255,255,255,.28)", backdropFilter: "blur(28px) saturate(145%)", WebkitBackdropFilter: "blur(28px) saturate(145%)"};
const at = (frame: number, duration: number, start: number, end: number, easing = appleEase) => interpolate(frame, [duration * start, duration * end], [0, 1], {...clamp, easing});
const normalizeItems = (items: AppleMotionProps["items"], fallback: string[]): AppleMotionItem[] => (items?.length ? items : fallback).map((item) => typeof item === "string" ? {label: item} : item);
const variantIcon: Record<AppleMotionVariant, LucideIconName> = {
  [AppleMotionVariant.DarkStage]: "microchip", [AppleMotionVariant.LightStage]: "panels-top-left",
  [AppleMotionVariant.GlassButton]: "mouse-pointer-click", [AppleMotionVariant.Toggle]: "toggle-right",
  [AppleMotionVariant.SegmentControl]: "settings", [AppleMotionVariant.Metric]: "gauge",
  [AppleMotionVariant.LineChart]: "chart-no-axes-combined", [AppleMotionVariant.Comparison]: "activity",
  [AppleMotionVariant.DataFlow]: "route", [AppleMotionVariant.Table]: "table-2",
  [AppleMotionVariant.ScreenWindow]: "monitor", [AppleMotionVariant.PresenterGraphic]: "presentation",
  [AppleMotionVariant.BigStatement]: "zap", [AppleMotionVariant.ProcessNetwork]: "network",
  [AppleMotionVariant.SummarySteps]: "list-checks",
};
const arcPath = (values: number[], width: number, height: number) => values.map((v, i) => {const x = i * width / Math.max(1, values.length - 1); const y = height - v * height; if (!i) return `M ${x} ${y}`; const px = (i - 1) * width / Math.max(1, values.length - 1); const py = height - values[i - 1] * height; const mid = (px + x) / 2; return `C ${mid} ${py},${mid} ${y},${x} ${y}`;}).join(" ");

const AudioCues: React.FC<{enabled: boolean; variant: AppleMotionVariant; duration: number}> = ({enabled, variant, duration}) => {
  if (!enabled) return null;
  const cue = (ratio: number) => Math.max(0, Math.round(duration * ratio));
  const analytical = [AppleMotionVariant.LineChart, AppleMotionVariant.DataFlow, AppleMotionVariant.ProcessNetwork].includes(variant);
  const action: Partial<Record<AppleMotionVariant, number[]>> = {
    [AppleMotionVariant.GlassButton]: [.36, .47], [AppleMotionVariant.Toggle]: [.43], [AppleMotionVariant.SegmentControl]: [.48],
    [AppleMotionVariant.Metric]: [.64], [AppleMotionVariant.LineChart]: [.77], [AppleMotionVariant.Comparison]: [.69],
    [AppleMotionVariant.DataFlow]: [.72], [AppleMotionVariant.Table]: [.68], [AppleMotionVariant.ScreenWindow]: [.62],
    [AppleMotionVariant.PresenterGraphic]: [.58], [AppleMotionVariant.BigStatement]: [.68], [AppleMotionVariant.ProcessNetwork]: [.74],
    [AppleMotionVariant.SummarySteps]: [.72], [AppleMotionVariant.DarkStage]: [.67], [AppleMotionVariant.LightStage]: [.67],
  };
  return <><Sequence from={cue(.04)} durationInFrames={Math.max(1, cue(.18))}><Audio src={getSfxUrl("whoosh")} volume={0.2}/></Sequence>{analytical && <Sequence from={cue(.2)} durationInFrames={Math.max(1, cue(.52))}><Audio src={getSfxUrl("riser")} volume={0.12}/></Sequence>}{(action[variant] ?? []).map((ratio, i) => <Sequence key={`${ratio}-${i}`} from={cue(ratio)} durationInFrames={Math.max(1, cue(.12))}><Audio src={getSfxUrl(i ? "impact" : "click")} volume={i ? .16 : .34}/></Sequence>)}</>;
};

const Header: React.FC<{title: string; subtitle?: string; dark: boolean; frame: number; duration: number; icon: LucideIconName; primary: string}> = ({title, subtitle, dark, frame, duration, icon, primary}) => {
  const p = at(frame, duration, .03, .19); const sub = at(frame, duration, .12, .27);
  return <div style={{textAlign: "center", maxWidth: 920, margin: "0 auto 38px"}}><div style={{width:54,height:54,borderRadius:18,display:"grid",placeItems:"center",margin:"0 auto 18px",background:`${primary}18`,border:`1px solid ${primary}55`,boxShadow:`0 12px 34px ${primary}28`,opacity:p,transform:`translateY(${(1-p)*16}px) scale(${.78+p*.22})`}}><LucideIcon name={icon} size={27} color={primary}/></div><div style={{font: `700 58px/1.02 ${fonts.display}`, letterSpacing: "-.045em", color: dark ? "#f5f5f7" : "#1d1d1f", opacity: p, transform: `translateY(${(1-p)*30}px) scale(${.96+p*.04})`, filter: `blur(${(1-p)*9}px)`}}>{title}</div>{subtitle && <div style={{font: `23px/1.35 ${fonts.sans}`, color: dark ? "rgba(245,245,247,.62)" : "rgba(29,29,31,.62)", marginTop: 16, opacity: sub, transform: `translateY(${(1-sub)*16}px)`}}>{subtitle}</div>}</div>;
};
const Card: React.FC<{children: ReactNode; style?: CSSProperties; progress?: number}> = ({children, style, progress = 1}) => <div style={{...glass, borderRadius: 36, position: "relative", overflow: "hidden", opacity: progress, transform: `translateY(${(1-progress)*36}px) scale(${.95+progress*.05})`, ...style}}>{children}</div>;

const Stage: React.FC<{light?: boolean; title: string; subtitle?: string; primary: string; frame: number; duration: number}> = ({light, title, subtitle, primary, frame, duration}) => {
  const text = at(frame,duration,.02,.22); const orb = at(frame,duration,.12,.38); const payoff = at(frame,duration,.64,.82); const float = Math.sin(frame/18)*10;
  return <div style={{display:"flex",alignItems:"center",justifyContent:"space-between",width:"86%",gap:80}}><div style={{width:"57%",opacity:text,transform:`translateX(${(1-text)*-50}px)`}}><div style={{font:`700 78px/.98 ${fonts.display}`,letterSpacing:"-.055em",color:light?"#1d1d1f":"#f5f5f7"}}>{title}</div><div style={{font:`25px/1.45 ${fonts.sans}`,marginTop:24,color:light?"rgba(29,29,31,.6)":"rgba(245,245,247,.62)",maxWidth:620}}>{subtitle}</div></div><div style={{position:"relative",width:330,height:330,transform:`translateY(${float}px) rotateY(${(1-orb)*28+Math.sin(frame/40)*4}deg) rotateX(${(1-orb)*-14}deg) scale(${.72+orb*.28})`,transformStyle:"preserve-3d"}}><div style={{position:"absolute",inset:18,borderRadius:80,background:`radial-gradient(circle at 32% 25%,#fff,${primary} 22%,#5527d8 58%,#08030f 78%)`,boxShadow:`0 45px ${70+payoff*35}px ${primary}${payoff>.5?"88":"55"},inset -22px -30px 60px rgba(0,0,0,.55),inset 18px 18px 35px rgba(255,255,255,.45)`}}/><div style={{position:"absolute",inset:-8,borderRadius:92,border:"1px solid rgba(255,255,255,.24)",transform:`translateZ(-35px) rotate(${frame*.12}deg)`}}/><div style={{position:"absolute",inset:-34,borderRadius:"50%",border:`1px solid ${primary}55`,transform:`translateZ(-70px) rotate(${-frame*.08}deg) scale(${1+Math.sin(frame/24)*.025})`}}/><div style={{position:"absolute",inset:0,display:"grid",placeItems:"center",opacity:orb,filter:"drop-shadow(0 0 18px rgba(255,255,255,.45))"}}><LucideIcon name="microchip" size={76} color="#FFFFFF"/></div></div></div>;
};

const Interactive: React.FC<{variant: AppleMotionVariant; value: string|number; labels: string[]; frame:number; duration:number; primary:string}> = ({variant,value,labels,frame,duration,primary}) => {
  const enter=at(frame,duration,.05,.23); const hover=at(frame,duration,.25,.36); const press=at(frame,duration,.40,.47); const release=at(frame,duration,.47,.54); const cursor=at(frame,duration,.18,.34); const ripple=at(frame,duration,.46,.68);
  if(variant===AppleMotionVariant.GlassButton) return <div style={{display:"grid",placeItems:"center",position:"relative"}}><div style={{...glass,borderRadius:999,padding:"27px 58px",color:"white",font:`700 28px ${fonts.sans}`,position:"relative",overflow:"hidden",transform:`scale(${(.82+enter*.18)*(1+hover*.035-press*.07+release*.035)})`,boxShadow:`0 22px ${55+hover*25}px ${primary}${hover>.5?"66":"44"},inset 0 1px 0 white`}}>{value}<i style={{position:"absolute",left:"50%",top:"50%",width:180,height:180,borderRadius:"50%",border:"2px solid rgba(255,255,255,.7)",opacity:(1-ripple)*.7,transform:`translate(-50%,-50%) scale(${ripple*1.5})`}}/></div><div style={{position:"absolute",left:`${78-cursor*29}%`,top:`${95-cursor*46}%`,opacity:enter,transform:`scale(${.8+cursor*.2})`,fontSize:42,color:"white",filter:"drop-shadow(0 5px 5px rgba(0,0,0,.5))"}}>➤</div></div>;
  const switchP=at(frame,duration,.32,.52,Easing.inOut(Easing.cubic));
  if(variant===AppleMotionVariant.Toggle) return <div style={{display:"grid",placeItems:"center",opacity:enter}}><div style={{width:190,height:100,padding:8,borderRadius:999,background:`linear-gradient(135deg,${switchP>.5?primary:"#3a3a3c"},${switchP>.5?"#64d2ff":"#555"})`,boxShadow:`0 18px 50px ${primary}${Math.round(switchP*80).toString(16).padStart(2,"0")}`,position:"relative"}}><div style={{width:84,height:84,borderRadius:"50%",background:"linear-gradient(#fff,#e8e8ed)",boxShadow:"0 8px 18px rgba(0,0,0,.28)",transform:`translateX(${switchP*90}px) scale(${1-Math.sin(switchP*Math.PI)*.08})`}}/></div><div style={{font:`600 18px ${fonts.sans}`,color:"rgba(255,255,255,.6)",marginTop:18}}>{switchP<.8?"Nonaktif":"Aktif"}</div></div>;
  const selected=Math.min(labels.length-1,Math.max(0,Math.round(Number(value)||Math.min(1,labels.length-1)))); const move=at(frame,duration,.32,.58,Easing.inOut(Easing.cubic));
  return <div style={{...glass,display:"flex",padding:7,borderRadius:18,gap:3,width:"min(720px,78%)",margin:"0 auto",position:"relative",opacity:enter}}><div style={{position:"absolute",left:7,top:7,bottom:7,width:`calc((100% - 14px) / ${labels.length})`,borderRadius:13,background:"rgba(255,255,255,.2)",boxShadow:"0 5px 18px rgba(0,0,0,.18)",transform:`translateX(${move*selected*100}%)`}}/>{labels.map((label,i)=><div key={label} style={{flex:1,padding:"18px 20px",textAlign:"center",font:`600 19px ${fonts.sans}`,color:i===selected&&move>.65?"white":"rgba(255,255,255,.62)",zIndex:1}}>{label}</div>)}</div>;
};

const Metric: React.FC<{value:string|number;secondary:string|number;primary:string;frame:number;duration:number}> = ({value,secondary,primary,frame,duration}) => {const enter=at(frame,duration,.04,.22); const count=at(frame,duration,28/150,95/150,Easing.inOut(Easing.cubic)); const status=at(frame,duration,.64,.78); const raw=String(value); const match=raw.match(/^([^\d-]*)(-?\d+(?:[.,]\d+)?)(.*)$/); const numeric=match?Number(match[2].replace(",",".")):null; const decimals=match?.[2].match(/[.,](\d+)/)?.[1].length??0; const counted=numeric===null?raw:`${match?.[1]??""}${(numeric*count).toFixed(decimals)}${match?.[3]??""}`; return <Card progress={enter} style={{width:650,padding:"48px 54px"}}><div style={{font:`500 18px ${fonts.sans}`,color:"rgba(255,255,255,.58)",letterSpacing:".02em"}}>NILAI SAAT INI</div><div style={{font:`700 96px ${fonts.display}`,letterSpacing:"-.065em",color:"white",marginTop:12,fontVariantNumeric:"tabular-nums",transform:`scale(${.94+count*.06})`,transformOrigin:"left",textShadow:`0 0 ${count*35}px ${primary}55`}}>{counted}</div><div style={{display:"inline-flex",padding:"9px 14px",borderRadius:999,background:`${primary}22`,color:primary,font:`700 18px ${fonts.sans}`,opacity:status,transform:`translateY(${(1-status)*12}px)`}}>↗ {secondary}</div></Card>};

const LineChart:React.FC<{value:string|number;labels:string[];primary:string;frame:number;duration:number}>=({value,labels,primary,frame,duration})=>{const enter=at(frame,duration,.03,.2); const draw=at(frame,duration,28/150,115/150,Easing.inOut(Easing.cubic)); const done=at(frame,duration,115/150,125/150); const beat=done*(.82+.18*Math.sin(frame*.45)); const path=arcPath([.18,.25,.22,.42,.38,.62,.57,.82,.75,.91],800,270); return <Card progress={enter} style={{width:940,height:410,padding:"38px 45px"}}><div style={{display:"flex",justifyContent:"space-between",color:"white",fontFamily:fonts.sans}}><b style={{fontSize:35}}>{value}</b><span style={{color:primary,opacity:at(frame,duration,.66,.8)}}>+24,8%</span></div><svg viewBox="0 0 800 300" style={{width:"100%",marginTop:20,overflow:"visible"}}>{[60,130,200,270].map((y,i)=><line key={y} x1="0" y1={y} x2="800" y2={y} stroke="rgba(255,255,255,.08)" opacity={at(frame,duration,.12+i*.03,.3+i*.03)}/>) }<path d={path} fill="none" stroke={primary} strokeWidth="7" strokeLinecap="round" pathLength="1" strokeDasharray="1" strokeDashoffset={1-draw} style={{filter:`drop-shadow(0 0 14px ${primary})`}}/><circle cx="800" cy={24.3} r={7+beat*7} fill="white" stroke={primary} strokeWidth="5" opacity={done}/><circle cx="800" cy={24.3} r={12+beat*18} fill="none" stroke={primary} strokeWidth="2" opacity={done*(1-beat*.5)}/></svg><div style={{display:"flex",justifyContent:"space-between",color:"rgba(255,255,255,.4)",font:`14px ${fonts.sans}`}}>{(labels.length?labels:["JAN","MAR","MEI","JUL","SEP"]).map(x=><span key={x}>{x}</span>)}</div></Card>};

const Comparison:React.FC<{items:AppleMotionItem[];frame:number;duration:number;primary:string}>=({items,frame,duration,primary})=><div style={{display:"flex",gap:24,width:900}}>{items.slice(0,3).map((item,i)=>{const card=at(frame,duration,.06+i*.09,.27+i*.09); const bar=at(frame,duration,.35+i*.08,.72+i*.05,Easing.inOut(Easing.cubic)); return <Card key={item.label} progress={card} style={{flex:1,padding:"36px 32px",minHeight:235,border:i===1?`1px solid ${primary}`:glass.border}}><div style={{color:"rgba(255,255,255,.55)",font:`18px ${fonts.sans}`}}>{item.label}</div><div style={{color:"white",font:`700 49px ${fonts.display}`,letterSpacing:"-.05em",marginTop:36}}>{item.value??`${42+i*21}%`}</div><div style={{height:5,borderRadius:9,marginTop:24,background:"rgba(255,255,255,.1)"}}><div style={{height:"100%",width:`${(45+i*20)*bar}%`,borderRadius:9,background:item.color??primary,boxShadow:`0 0 16px ${item.color??primary}`}}/></div></Card>})}</div>;

const DataFlow:React.FC<{items:AppleMotionItem[];frame:number;duration:number;primary:string}>=({items,frame,duration,primary})=>{const shown=items.slice(0,4); return <div style={{display:"flex",alignItems:"center",width:950,justifyContent:"space-between"}}>{shown.map((item,i)=>{const node=at(frame,duration,.04+i*.1,.24+i*.1); return <React.Fragment key={item.label}><div style={{...glass,width:150,height:150,borderRadius:42,display:"grid",placeItems:"center",color:"white",font:`600 18px ${fonts.sans}`,textAlign:"center",transform:`translateY(${Math.sin(frame/22+i*1.8)*9}px) scale(${.8+node*.2})`,opacity:node}}><div><div style={{width:12,height:12,borderRadius:9,background:item.color??primary,boxShadow:`0 0 22px ${item.color??primary}`,margin:"0 auto 14px"}}/>{item.label}</div></div>{i<shown.length-1&&<Connection index={i} frame={frame} duration={duration} primary={primary}/>}</React.Fragment>})}</div>};
const Connection:React.FC<{index:number;frame:number;duration:number;primary:string}>=({index,frame,duration,primary})=>{const line=at(frame,duration,.22+index*.11,.48+index*.11,Easing.inOut(Easing.cubic)); const travel=Math.max(0,((frame-duration*(.3+index*.08))/(duration*.28))%1); return <div style={{height:20,flex:1,position:"relative",overflow:"hidden"}}><div style={{position:"absolute",left:0,right:0,top:9,height:2,background:`linear-gradient(90deg,${primary},${primary}66)`,transform:`scaleX(${line})`,transformOrigin:"left"}}/><div style={{position:"absolute",left:`${travel*100}%`,top:4,width:12,height:12,borderRadius:"50%",background:"white",opacity:line>.75?1:0,boxShadow:`0 0 18px 6px ${primary}`}}/></div>};

const Table:React.FC<{items:AppleMotionItem[];labels:string[];frame:number;duration:number;primary:string}>=({items,labels,frame,duration,primary})=>{const enter=at(frame,duration,.03,.2); return <Card progress={enter} style={{width:950,padding:"18px 32px"}}><div style={{display:"grid",gridTemplateColumns:"1.4fr 1fr 1fr",color:"rgba(255,255,255,.4)",padding:"18px 12px",font:`600 14px ${fonts.sans}`,letterSpacing:".08em"}}>{(labels.length?labels:["NAMA","NILAI","STATUS"]).slice(0,3).map(x=><span key={x}>{x}</span>)}</div>{items.slice(0,5).map((item,i)=>{const row=at(frame,duration,.27+i*.085,.42+i*.085); return <div key={item.label} style={{display:"grid",gridTemplateColumns:"1.4fr 1fr 1fr",color:"white",padding:"20px 12px",borderTop:"1px solid rgba(255,255,255,.09)",font:`17px ${fonts.sans}`,opacity:row,transform:`translateX(${(1-row)*24}px)`}}><b>{item.label}</b><span>{item.value??`${88-i*7}%`}</span><span style={{color:item.color??primary}}>● {item.detail??"Aktif"}</span></div>})}</Card>};

const ScreenWindow:React.FC<{title:string;primary:string;frame:number;duration:number}>=({title,primary,frame,duration})=>{const enter=at(frame,duration,.02,.2); const settle=at(frame,duration,.08,.4,Easing.inOut(Easing.cubic)); return <div style={{perspective:1100}}><Card progress={enter} style={{width:900,height:455,transform:`rotateX(${(1-settle)*15}deg) rotateY(${(1-settle)*-18}deg) translateY(${(1-settle)*42}px) scale(${.94+settle*.06})`,boxShadow:`40px 55px 100px rgba(0,0,0,.48),-20px -10px 70px ${primary}22`}}><div style={{height:54,borderBottom:"1px solid rgba(255,255,255,.1)",display:"flex",alignItems:"center",padding:"0 22px",gap:9}}>{[PINK,ORANGE,GREEN].map(c=><i key={c} style={{width:12,height:12,borderRadius:9,background:c}}/>)}<span style={{margin:"auto",color:"rgba(255,255,255,.45)",font:`14px ${fonts.sans}`}}>{title}</span></div><div style={{padding:45,display:"grid",gridTemplateColumns:"1.2fr .8fr",gap:32}}><div style={{height:290,borderRadius:24,background:`radial-gradient(circle at ${38+Math.sin(frame/30)*3}% 35%,${primary},#4b1fb8 42%,#090a12 75%)`}}/><div>{[.85,.55,.72,.4].map((w,i)=>{const row=at(frame,duration,.34+i*.08,.48+i*.08); return <div key={i} style={{height:i===0?24:13,width:`${w*100}%`,borderRadius:9,background:i===0?"white":"rgba(255,255,255,.15)",marginBottom:24,opacity:row,transform:`translateX(${(1-row)*25}px)`}}/>})}</div></div></Card></div>};

const PresenterGraphic:React.FC<{primary:string;frame:number;duration:number}>=({primary,frame,duration})=>{const person=at(frame,duration,.04,.28); const card=at(frame,duration,.25,.52); const accent=at(frame,duration,.48,.72); return <div style={{width:850,height:390,position:"relative"}}><div style={{position:"absolute",left:50,bottom:0,width:250,height:250,borderRadius:"50% 50% 42% 42%",background:`radial-gradient(circle at 45% 30%,#ffd4bd 0 24%,#17171b 25% 45%,${primary} 46% 100%)`,boxShadow:`0 35px 80px ${primary}44`,opacity:person,transform:`translateX(${(1-person)*-70}px) translateY(${Math.sin(frame/28)*4}px)`}}/><Card progress={card} style={{position:"absolute",right:0,top:25,width:510,padding:42,transform:`translateX(${(1-card)*70}px) scale(${.96+card*.04})`}}><div style={{font:`700 35px ${fonts.display}`,color:"white"}}>Dirancang agar tetap fokus.</div><div style={{height:5,background:primary,borderRadius:9,width:`${accent*80}%`,margin:"30px 0"}}/><div style={{font:`20px/1.5 ${fonts.sans}`,color:"rgba(255,255,255,.55)",opacity:accent}}>Antarmuka tenang yang mengutamakan hal terpenting.</div></Card></div>};

const BigStatement:React.FC<{title:string;subtitle?:string;primary:string;frame:number;duration:number}>=({title,subtitle,primary,frame,duration})=>{const words=title.split(" "); const sub=at(frame,duration,.58,.76); return <div style={{textAlign:"center",width:"92%"}}><div style={{font:`700 104px/.95 ${fonts.display}`,letterSpacing:"-.07em",color:"white",textShadow:`0 18px 80px ${primary}55`}}>{words.map((word,i)=>{const p=at(frame,duration,.04+i*.055,.23+i*.055); return <span key={`${word}-${i}`} style={{display:"inline-block",marginRight:".22em",opacity:p,transform:`translateY(${(1-p)*48}px) scale(${.9+p*.1})`,filter:`blur(${(1-p)*18}px)`}}>{word}</span>})}</div>{subtitle&&<div style={{font:`24px ${fonts.sans}`,color:"rgba(255,255,255,.55)",marginTop:38,opacity:sub,transform:`translateY(${(1-sub)*18}px)`}}>{subtitle}</div>}</div>};

const ProcessNetwork:React.FC<{items:AppleMotionItem[];frame:number;duration:number;primary:string}>=({items,frame,duration,primary})=>{const nodes=items.slice(0,6); return <div style={{position:"relative",width:900,height:400}}><svg viewBox="0 0 900 400" style={{position:"absolute",inset:0,overflow:"visible"}}>{nodes.slice(1).map((_,i)=>{const p=at(frame,duration,.18+i*.08,.39+i*.08); const x=140+(i%3)*310; const y=i<3?65:340; return <line key={i} x1="450" y1="200" x2={x} y2={y} stroke={primary} strokeOpacity=".5" strokeWidth="2" pathLength="1" strokeDasharray="1" strokeDashoffset={1-p}/>})}<circle cx={450+Math.cos(frame/18)*104} cy={200+Math.sin(frame/18)*104} r="5" fill="white" opacity={at(frame,duration,.65,.76)} style={{filter:`drop-shadow(0 0 9px ${primary})`}}/></svg>{nodes.map((item,i)=>{const center=i===0; const index=i-1; const x=center?450:140+(index%3)*310; const y=center?200:index<3?65:340; const p=at(frame,duration,center?.04:.3+index*.08,center?.24:.47+index*.08); const pulse=center?1+Math.sin(frame/12)*.035:1+Math.sin(frame/17+i)*.018; return <div key={item.label} style={{...glass,position:"absolute",left:x-(center?78:60),top:y-(center?78:60),width:center?156:120,height:center?156:120,borderRadius:"50%",display:"grid",placeItems:"center",textAlign:"center",color:"white",font:`600 ${center?19:15}px ${fonts.sans}`,boxShadow:center?`0 0 65px ${primary}66`:glass.boxShadow,opacity:p,transform:`scale(${(.68+p*.32)*pulse})`}}>{item.label}</div>})}</div>};

const SummarySteps:React.FC<{items:AppleMotionItem[];frame:number;duration:number;primary:string}>=({items,frame,duration,primary})=><div style={{display:"flex",gap:18,width:980}}>{items.slice(0,5).map((item,i)=>{const p=at(frame,duration,.1+i*.105,.28+i*.105); const active=at(frame,duration,.55+i*.055,.7+i*.055); return <div key={item.label} style={{flex:1,opacity:p,transform:`translateY(${(1-p)*36}px)`}}><div style={{font:`700 46px ${fonts.display}`,color:`color-mix(in srgb,${primary} ${active*100}%,rgba(255,255,255,.24))`}}>0{i+1}</div><div style={{height:2,background:`linear-gradient(90deg,${primary} ${active*100}%,rgba(255,255,255,.16) 0)`,margin:"18px 0 22px"}}/><div style={{font:`600 19px/1.3 ${fonts.sans}`,color:"white"}}>{item.label}</div><div style={{font:`15px/1.4 ${fonts.sans}`,color:"rgba(255,255,255,.44)",marginTop:10}}>{item.detail}</div></div>})}</div>;

export const AppleMotion:React.FC<AppleMotionProps>=({variant,title="Dirancang untuk langkah berikutnya.",subtitle="Ide kuat yang disampaikan dengan jelas.",primary=BLUE,background,value="Lanjutkan",secondaryValue="+18,4%",labels=[],items,audioEnabled=false})=>{
  const frame=useCurrentFrame(); const {width,height,durationInFrames}=useVideoConfig(); const duration=Math.max(1,durationInFrames); const isLight=variant===AppleMotionVariant.LightStage; const bg=background??(isLight?LIGHT:DARK); const normalized=normalizeItems(items,["Temukan","Rancang","Bangun","Sempurnakan","Kirim","Kembangkan"]); const scale=Math.min(width/1280,height/720); const commonHeader=![AppleMotionVariant.DarkStage,AppleMotionVariant.LightStage,AppleMotionVariant.BigStatement].includes(variant); const orbEnter=at(frame,duration,0,.22); const living=.96+Math.sin(frame/22)*.04; let content:ReactNode;
  switch(variant){
    case AppleMotionVariant.DarkStage:content=<Stage title={title} subtitle={subtitle} primary={primary} frame={frame} duration={duration}/>;break;
    case AppleMotionVariant.LightStage:content=<Stage light title={title} subtitle={subtitle} primary={primary} frame={frame} duration={duration}/>;break;
    case AppleMotionVariant.GlassButton:case AppleMotionVariant.Toggle:case AppleMotionVariant.SegmentControl:content=<Interactive variant={variant} value={value} labels={labels.length?labels:["Ringkasan","Detail","Wawasan"]} frame={frame} duration={duration} primary={primary}/>;break;
    case AppleMotionVariant.Metric:content=<Metric value={value} secondary={secondaryValue} primary={primary} frame={frame} duration={duration}/>;break;
    case AppleMotionVariant.LineChart:content=<LineChart value={value} labels={labels} primary={primary} frame={frame} duration={duration}/>;break;
    case AppleMotionVariant.Comparison:content=<Comparison items={normalized} frame={frame} duration={duration} primary={primary}/>;break;
    case AppleMotionVariant.DataFlow:content=<DataFlow items={normalized} frame={frame} duration={duration} primary={primary}/>;break;
    case AppleMotionVariant.Table:content=<Table items={normalized} labels={labels} frame={frame} duration={duration} primary={primary}/>;break;
    case AppleMotionVariant.ScreenWindow:content=<ScreenWindow title={title} primary={primary} frame={frame} duration={duration}/>;break;
    case AppleMotionVariant.PresenterGraphic:content=<PresenterGraphic primary={primary} frame={frame} duration={duration}/>;break;
    case AppleMotionVariant.BigStatement:content=<BigStatement title={title} subtitle={subtitle} primary={primary} frame={frame} duration={duration}/>;break;
    case AppleMotionVariant.ProcessNetwork:content=<ProcessNetwork items={normalized} frame={frame} duration={duration} primary={primary}/>;break;
    case AppleMotionVariant.SummarySteps:content=<SummarySteps items={normalized} frame={frame} duration={duration} primary={primary}/>;break;
    default:content=null;
  }
  return <AbsoluteFill style={{background:bg,overflow:"hidden"}}><AudioCues enabled={audioEnabled} variant={variant} duration={duration}/><div style={{position:"absolute",width:680*scale,height:680*scale,left:`calc(50% - ${340*scale}px)`,top:`calc(50% - ${340*scale}px)`,borderRadius:"50%",background:`radial-gradient(circle,${primary}38 0%,${primary}12 38%,transparent 70%)`,filter:"blur(18px)",opacity:orbEnter,transform:`translate(${Math.sin(frame/37)*12}px,${Math.cos(frame/31)*9}px) scale(${living})`}}/><div style={{position:"absolute",inset:0,opacity:.035,backgroundImage:"url(\"data:image/svg+xml,%3Csvg viewBox='0 0 180 180' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='.9' numOctaves='3' stitchTiles='stitchTiles'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='.85'/%3E%3C/svg%3E\")",mixBlendMode:isLight?"multiply":"screen"}}/><div style={{position:"absolute",left:"50%",top:"50%",width:1280,height:720,transform:`translate(-50%,-50%) scale(${scale})`,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",padding:"62px 80px",boxSizing:"border-box",perspective:1200}}>{commonHeader&&<Header title={title} subtitle={subtitle} dark={!isLight} frame={frame} duration={duration} icon={variantIcon[variant]} primary={primary}/>} {content}</div></AbsoluteFill>;
};
