import React, {type CSSProperties, type ReactNode} from "react";
import {AbsoluteFill, Audio, Easing, Sequence, interpolate, useCurrentFrame, useVideoConfig} from "remotion";
import {fonts} from "../../fonts";
import {getSfxUrl} from "../../sfx/synth";
import {LucideIcon, type LucideIconName} from "./LucideIcon";

export enum AppleMotionVariant {
  DarkStage = "dark-stage", LightStage = "light-stage", GlassButton = "glass-button", Toggle = "toggle",
  SegmentControl = "segment-control", Metric = "metric", LineChart = "line-chart", Comparison = "comparison",
  DataFlow = "data-flow", Table = "table", ScreenWindow = "screen-window", PresenterGraphic = "presenter-graphic",
  BigStatement = "big-statement", ProcessNetwork = "process-network", SummarySteps = "summary-steps",
}

export interface AppleMotionItem {label: string; value?: string | number; detail?: string; color?: string}
export interface AppleMotionProps {
  variant: AppleMotionVariant; title?: string; subtitle?: string; primary?: string; background?: string;
  value?: string | number; secondaryValue?: string | number; labels?: string[];
  items?: Array<AppleMotionItem | string>; icon?: LucideIconName | "none"; audioEnabled?: boolean;
}

const DARK = "#050506";
const LIGHT = "#f5f5f7";
const BLUE = "#2997ff";
const clamp = {extrapolateLeft: "clamp", extrapolateRight: "clamp"} as const;
const editorialEase = Easing.bezier(.16, 1, .3, 1);
const tactileEase = Easing.bezier(.2, .9, .25, 1.18);
const mechanicalEase = Easing.bezier(.65, 0, .35, 1);
const at = (frame:number,duration:number,start:number,end:number,easing=editorialEase) => interpolate(frame,[duration*start,duration*end],[0,1],{...clamp,easing});
const mix = (a:number,b:number,p:number) => a+(b-a)*p;
const normalizeItems = (items:AppleMotionProps["items"],fallback:string[]):AppleMotionItem[] => (items?.length?items:fallback).map(item=>typeof item==="string"?{label:item}:item);
const glass:CSSProperties = {background:"linear-gradient(145deg,rgba(255,255,255,.115),rgba(255,255,255,.035))",border:"1px solid rgba(255,255,255,.16)",boxShadow:"0 26px 70px rgba(0,0,0,.28),inset 0 1px rgba(255,255,255,.2)",backdropFilter:"blur(24px) saturate(125%)",WebkitBackdropFilter:"blur(24px) saturate(125%)"};
const variantIcon:Record<AppleMotionVariant,LucideIconName> = {
  [AppleMotionVariant.DarkStage]:"microchip",[AppleMotionVariant.LightStage]:"panels-top-left",[AppleMotionVariant.GlassButton]:"mouse-pointer-click",
  [AppleMotionVariant.Toggle]:"toggle-right",[AppleMotionVariant.SegmentControl]:"settings",[AppleMotionVariant.Metric]:"gauge",
  [AppleMotionVariant.LineChart]:"chart-no-axes-combined",[AppleMotionVariant.Comparison]:"activity",[AppleMotionVariant.DataFlow]:"route",
  [AppleMotionVariant.Table]:"table-2",[AppleMotionVariant.ScreenWindow]:"monitor",[AppleMotionVariant.PresenterGraphic]:"presentation",
  [AppleMotionVariant.BigStatement]:"zap",[AppleMotionVariant.ProcessNetwork]:"network",[AppleMotionVariant.SummarySteps]:"list-checks",
};

const AudioCues:React.FC<{enabled:boolean;variant:AppleMotionVariant;duration:number}> = ({enabled,variant,duration}) => {
  if(!enabled)return null;
  const cue=(ratio:number)=>Math.max(0,Math.round(duration*ratio));
  const analytical=[AppleMotionVariant.LineChart,AppleMotionVariant.DataFlow,AppleMotionVariant.ProcessNetwork].includes(variant);
  const payoff:Partial<Record<AppleMotionVariant,number>>={
    [AppleMotionVariant.DarkStage]:.58,[AppleMotionVariant.LightStage]:.62,[AppleMotionVariant.GlassButton]:.55,[AppleMotionVariant.Toggle]:.56,
    [AppleMotionVariant.SegmentControl]:.63,[AppleMotionVariant.Metric]:.65,[AppleMotionVariant.LineChart]:.76,[AppleMotionVariant.Comparison]:.66,
    [AppleMotionVariant.DataFlow]:.73,[AppleMotionVariant.Table]:.72,[AppleMotionVariant.ScreenWindow]:.68,[AppleMotionVariant.PresenterGraphic]:.6,
    [AppleMotionVariant.BigStatement]:.39,[AppleMotionVariant.ProcessNetwork]:.76,[AppleMotionVariant.SummarySteps]:.78,
  };
  return <><Sequence from={cue(.025)} durationInFrames={Math.max(1,cue(.2))}><Audio src={getSfxUrl("whoosh")} volume={.14}/></Sequence>{analytical&&<Sequence from={cue(.26)} durationInFrames={Math.max(1,cue(.45))}><Audio src={getSfxUrl("riser")} volume={.08}/></Sequence>}<Sequence from={cue(payoff[variant]??.65)} durationInFrames={Math.max(1,cue(.14))}><Audio src={getSfxUrl("impact")} volume={.2}/></Sequence></>;
};

const LightField:React.FC<{primary:string;frame:number;duration:number;light?:boolean;focus?:[number,number];payoff?:number}> = ({primary,frame,duration,light,focus=[62,45],payoff=0}) => {
  const enter=at(frame,duration,0,.2); const breathe=1+Math.sin(frame/34)*.018;
  return <><div style={{position:"absolute",width:"58%",height:"75%",left:`${focus[0]-29}%`,top:`${focus[1]-37}%`,borderRadius:"50%",background:`radial-gradient(circle,${primary}${light?"16":"24"} 0%,${primary}${light?"08":"0c"} 34%,transparent 70%)`,filter:"blur(34px)",opacity:enter*(.72+payoff*.28),transform:`scale(${breathe*(.94+payoff*.08)})`}}/><div style={{position:"absolute",width:"34%",height:"45%",left:`${focus[0]-17}%`,top:`${focus[1]-22}%`,borderRadius:"50%",background:`radial-gradient(circle,rgba(255,255,255,${light?.16:.2}),transparent 66%)`,filter:"blur(18px)",opacity:enter*(.28+payoff*.28)}}/><div style={{position:"absolute",inset:0,opacity:light?.022:.028,backgroundImage:"url(\"data:image/svg+xml,%3Csvg viewBox='0 0 180 180' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='.9' numOctaves='3'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)'/%3E%3C/svg%3E\")",mixBlendMode:light?"multiply":"screen"}}/></>;
};

const Eyebrow:React.FC<{children:ReactNode;color?:string;progress?:number}> = ({children,color="rgba(255,255,255,.48)",progress=1}) => <div style={{font:`700 12px ${fonts.mono}`,letterSpacing:".16em",textTransform:"uppercase",color,opacity:progress,transform:`translateY(${(1-progress)*10}px)`}}>{children}</div>;
const MaskLine:React.FC<{children:ReactNode;progress:number;style?:CSSProperties}> = ({children,progress,style}) => <div style={{overflow:"hidden",...style}}><div style={{transform:`translateY(${(1-progress)*112}%)`,opacity:progress,filter:`blur(${(1-progress)*5}px)`}}>{children}</div></div>;
const IconBox:React.FC<{icon?:LucideIconName;primary:string;size?:number;progress?:number;rotate?:number;style?:CSSProperties}> = ({icon,primary,size=34,progress=1,rotate=0,style}) => icon?<div style={{display:"grid",placeItems:"center",opacity:progress,transform:`scale(${.72+progress*.28}) rotate(${rotate}deg)`,...style}}><LucideIcon name={icon} size={size} color={primary}/></div>:null;

const DarkStage:React.FC<{title:string;subtitle?:string;primary:string;frame:number;duration:number;icon?:LucideIconName}> = ({title,subtitle,primary,frame,duration,icon}) => {
  const silhouette=at(frame,duration,.03,.16); const edge=at(frame,duration,.1,.28); const titleIn=at(frame,duration,.17,.35); const sub=at(frame,duration,.3,.46); const pins=at(frame,duration,.36,.55,mechanicalEase); const activate=at(frame,duration,.52,.64,tactileEase); const settle=at(frame,duration,.64,.78); const scan=mix(-30,125,edge);
  return <><LightField primary={primary} frame={frame} duration={duration} focus={[72,48]} payoff={activate}/><div style={{position:"absolute",left:76,top:76,width:575,zIndex:2}}><Eyebrow progress={titleIn} color={`${primary}cc`}>SISTEM · AKTIVASI</Eyebrow><MaskLine progress={titleIn} style={{marginTop:18,font:`700 72px/.97 ${fonts.display}`,letterSpacing:"-.06em"}}>{title}</MaskLine><div style={{font:`21px/1.5 ${fonts.sans}`,color:"rgba(255,255,255,.53)",maxWidth:510,marginTop:24,opacity:sub,transform:`translateY(${(1-sub)*16}px)`}}>{subtitle}</div></div><div style={{position:"absolute",right:104,top:142,width:360,height:360,perspective:900}}><div style={{position:"absolute",inset:25,borderRadius:82,background:`linear-gradient(145deg,#101419,${primary}18 48%,#070809)`,border:`1px solid rgba(255,255,255,${.05+edge*.18})`,boxShadow:`0 38px 85px rgba(0,0,0,.48),inset 0 0 54px ${primary}${activate>.5?"2e":"14"}`,opacity:silhouette,transform:`rotateX(${(1-settle)*13}deg) rotateY(${(1-settle)*-19}deg) scale(${.86+settle*.14+Math.sin(activate*Math.PI)*.025})`,overflow:"hidden"}}><div style={{position:"absolute",top:0,bottom:0,left:`${scan}%`,width:90,background:"linear-gradient(90deg,transparent,rgba(255,255,255,.34),transparent)",filter:"blur(8px)",transform:"skewX(-18deg)"}}/><IconBox icon={icon} primary={activate>.3?"#fff":primary} size={112} progress={pins} style={{position:"absolute",inset:0,filter:`drop-shadow(0 0 ${8+activate*18}px ${primary})`}}/>{[0,1,2,3].map(side=><div key={side} style={{position:"absolute",left:side<2?`${25+side*50}%`:side===2?-9:undefined,right:side===3?-9:undefined,top:side>=2?"25%":side===0?-9:undefined,bottom:side===1?-9:undefined,width:side<2?3:18,height:side<2?18:3,background:primary,boxShadow:`0 0 11px ${primary}`,opacity:at(frame,duration,.4+side*.025,.48+side*.025)}}/>)}</div>{[0,1].map(i=><div key={i} style={{position:"absolute",inset:-8-i*28,borderRadius:i?"50%":96,border:`1px solid ${primary}${i?"28":"48"}`,opacity:edge,transform:`rotate(${(i?1:-1)*frame*.08}deg) scale(${1+activate*(i?.035:.02)})`}}/>)}<div style={{position:"absolute",left:"50%",top:"50%",width:18+activate*330,height:18+activate*330,borderRadius:"50%",border:`2px solid ${primary}`,opacity:activate*(1-settle),transform:"translate(-50%,-50%)"}}/></div></>;
};

const LightStage:React.FC<{title:string;subtitle?:string;primary:string;frame:number;duration:number;icon?:LucideIconName}> = ({title,subtitle,primary,frame,duration,icon}) => {
  const label=at(frame,duration,.04,.18); const type=at(frame,duration,.12,.34); const italic=at(frame,duration,.22,.4); const panels=at(frame,duration,.18,.52,mechanicalEase); const lock=at(frame,duration,.54,.67,tactileEase); const sub=at(frame,duration,.48,.66);
  return <><LightField light primary={primary} frame={frame} duration={duration} focus={[68,46]} payoff={lock}/><div style={{position:"absolute",left:82,top:82,width:575,zIndex:2}}><Eyebrow color="#6e6e73" progress={label}>EDISI PRODUK · 02</Eyebrow><MaskLine progress={type} style={{font:`400 78px/.93 ${fonts.classic}`,color:"#18181a",marginTop:24,letterSpacing:"-.035em"}}>{title.split(" ").slice(0,-2).join(" ")||title}</MaskLine><MaskLine progress={italic} style={{font:`700 70px/.98 ${fonts.playfair}`,color:primary,marginTop:4}}>{title.split(" ").slice(-2).join(" ")}</MaskLine><div style={{width:48,height:2,background:primary,marginTop:28,transform:`scaleX(${sub})`,transformOrigin:"left"}}/><div style={{font:`18px/1.55 ${fonts.sans}`,color:"rgba(29,29,31,.58)",maxWidth:470,marginTop:18,opacity:sub}}>{subtitle}</div></div><div style={{position:"absolute",right:105,top:130,width:390,height:390}}>{[0,1,2].map(i=>{const p=at(frame,duration,.18+i*.08,.42+i*.08,mechanicalEase); const positions=[[0,78],[118,0],[118,118]]; return <div key={i} style={{position:"absolute",left:positions[i][0],top:positions[i][1],width:i?230:105,height:i===2?230:105,borderRadius:30,background:`linear-gradient(145deg,rgba(255,255,255,.82),${primary}${i===2?"18":"0d"})`,border:"1px solid rgba(29,29,31,.12)",boxShadow:"0 24px 55px rgba(34,40,45,.11),inset 0 1px white",backdropFilter:"blur(22px)",opacity:p,transform:`translate(${(1-p)*(i===0?-90:70)}px,${(1-p)*(i===1?-70:65)}px) rotate(${(1-p)*(i===0?-8:6)}deg)`}}/>})}<IconBox icon={icon} primary="#202124" size={94} progress={lock} rotate={(1-lock)*-18} style={{position:"absolute",left:118,top:118,width:230,height:230,filter:`drop-shadow(0 12px 18px ${primary}30)`}}/><div style={{position:"absolute",left:110,top:110,width:246,height:246,borderRadius:36,border:`2px solid ${primary}`,opacity:lock*(1-at(frame,duration,.68,.78)),transform:`scale(${.9+lock*.16})`}}/></div></>;
};

const InteractionTitle:React.FC<{title:string;subtitle?:string;primary:string;frame:number;duration:number;index:string}> = ({title,subtitle,primary,frame,duration,index}) => {const a=at(frame,duration,.02,.18);const b=at(frame,duration,.1,.25);return <div style={{position:"absolute",left:82,top:70,width:520}}><Eyebrow progress={a} color={`${primary}bb`}>INTERAKSI · {index}</Eyebrow><div style={{font:`700 48px/1.02 ${fonts.display}`,letterSpacing:"-.05em",marginTop:15,opacity:a,transform:`translateY(${(1-a)*20}px)`}}>{title}</div><div style={{font:`17px/1.45 ${fonts.sans}`,color:"rgba(255,255,255,.48)",marginTop:13,opacity:b,maxWidth:480}}>{subtitle}</div></div>};

const GlassButton:React.FC<{title:string;subtitle?:string;value:string|number;primary:string;frame:number;duration:number;icon?:LucideIconName}> = ({title,subtitle,value,primary,frame,duration,icon}) => {
  const enter=at(frame,duration,.16,.32); const approach=at(frame,duration,.31,.47,mechanicalEase); const contact=at(frame,duration,.47,.53,Easing.in(Easing.cubic)); const release=at(frame,duration,.53,.63,tactileEase); const success=at(frame,duration,.61,.76); const ripple=at(frame,duration,.51,.73); const x=mix(300,18,approach); const y=mix(155,30,approach);
  return <><LightField primary={primary} frame={frame} duration={duration} focus={[62,61]} payoff={success}/><InteractionTitle title={title} subtitle={subtitle} primary={primary} frame={frame} duration={duration} index="KLIK"/><div style={{position:"absolute",left:"50%",top:"61%",transform:"translate(-50%,-50%)",zIndex:2}}><div style={{...glass,minWidth:360,padding:"25px 52px",borderRadius:999,textAlign:"center",font:`700 25px ${fonts.sans}`,overflow:"hidden",transform:`scale(${(.9+enter*.1)*(1-contact*.065+release*.03)})`,boxShadow:`0 22px 55px rgba(0,0,0,.3),0 0 ${success*28}px ${primary}35`,opacity:enter}}><span style={{opacity:1-success,transform:`translateY(${-success*18}px)`,display:"inline-block"}}>{value}</span><span style={{position:"absolute",inset:0,display:"flex",alignItems:"center",justifyContent:"center",gap:12,opacity:success,transform:`translateY(${(1-success)*18}px)`,color:"white"}}><LucideIcon name="list-checks" size={27} color={primary}/>Berhasil diterapkan</span><i style={{position:"absolute",left:`${50+x/10}%`,top:`${50+y/10}%`,width:150,height:150,borderRadius:"50%",border:"2px solid rgba(255,255,255,.65)",opacity:(1-ripple)*.65,transform:`translate(-50%,-50%) scale(${ripple*1.6})`}}/></div>{icon&&<div style={{position:"absolute",left:x,top:y,opacity:enter,transform:`rotate(${(1-approach)*-11}deg) scale(${1-contact*.17+release*.08})`,filter:"drop-shadow(0 5px 6px rgba(0,0,0,.65))"}}><LucideIcon name={icon} size={45} color="#fff"/></div>}</div></>;
};

const Toggle:React.FC<{title:string;subtitle?:string;primary:string;frame:number;duration:number;icon?:LucideIconName}> = ({title,subtitle,primary,frame,duration,icon}) => {
  const enter=at(frame,duration,.17,.31); const pointer=at(frame,duration,.3,.45,mechanicalEase); const press=at(frame,duration,.45,.51); const pulse=at(frame,duration,.49,.58); const move=at(frame,duration,.52,.65,tactileEase); const done=at(frame,duration,.64,.77); const thumbX=move<.78?move/ .78*96:96+(move-.78)/.22*7*(1-(move-.78)/.22);
  return <><LightField primary={primary} frame={frame} duration={duration} focus={[62,62]} payoff={done}/><InteractionTitle title={title} subtitle={subtitle} primary={primary} frame={frame} duration={duration} index="SAKELAR"/><div style={{position:"absolute",left:"50%",top:"62%",transform:"translate(-50%,-50%)"}}><div style={{width:210,height:106,padding:9,borderRadius:999,background:`linear-gradient(100deg,#303136 ${Math.max(0,50-move*50)}%,${primary} ${Math.min(100,move*120)}%)`,boxShadow:`0 22px 55px rgba(0,0,0,.35),0 0 ${done*30}px ${primary}30`,opacity:enter,transform:`scale(${.9+enter*.1-press*.025})`,position:"relative"}}><div style={{width:88,height:88,borderRadius:"50%",background:"linear-gradient(#fff,#e7e8eb)",boxShadow:"0 8px 20px rgba(0,0,0,.3)",transform:`translateX(${thumbX}px) scaleX(${1+Math.sin(move*Math.PI)*.1})`}}/><div style={{position:"absolute",left:105,top:53,width:pulse*190,height:pulse*190,borderRadius:"50%",border:`2px solid ${primary}`,opacity:pulse*(1-done),transform:"translate(-50%,-50%)"}}/></div>{icon&&<div style={{position:"absolute",left:210-pointer*92,top:96-pointer*67,opacity:enter,transform:`scale(${1-press*.16})`}}><LucideIcon name={icon} size={40} color="#fff"/></div>}<div style={{textAlign:"center",marginTop:20,font:`700 12px ${fonts.mono}`,letterSpacing:".12em",color:done?primary:"rgba(255,255,255,.38)",opacity:enter}}>{done>.75?"PERFORMA AKTIF":"SIAP DIAKTIFKAN"}</div></div></>;
};

const SegmentControl:React.FC<{title:string;subtitle?:string;value:string|number;labels:string[];primary:string;frame:number;duration:number;icon?:LucideIconName}> = ({title,subtitle,value,labels,primary,frame,duration,icon}) => {
  const enter=at(frame,duration,.15,.29); const inspect1=at(frame,duration,.3,.42,mechanicalEase); const inspect2=at(frame,duration,.43,.54,mechanicalEase); const select=at(frame,duration,.55,.68,tactileEase); const done=at(frame,duration,.68,.8); const selected=Math.min(labels.length-1,Math.max(0,Math.round(Number(value)||labels.length-1))); const focusPos=inspect2<1?inspect1*Math.min(1,selected):mix(Math.min(1,selected),selected,select);
  return <><LightField primary={primary} frame={frame} duration={duration} focus={[63,60]} payoff={done}/><InteractionTitle title={title} subtitle={subtitle} primary={primary} frame={frame} duration={duration} index="MODE"/><div style={{position:"absolute",left:"50%",top:"61%",width:850,transform:"translate(-50%,-50%)",display:"flex",alignItems:"center",gap:24}}><IconBox icon={icon} primary={done?primary:"rgba(255,255,255,.7)"} size={42} progress={enter} rotate={select*150+inspect1*45+inspect2*45} style={{width:66,height:66,borderRadius:22,...glass}}/><div style={{...glass,display:"flex",padding:7,borderRadius:20,flex:1,position:"relative",opacity:enter,transform:`translateY(${(1-enter)*25}px)`}}><div style={{position:"absolute",left:7,top:7,bottom:7,width:`calc((100% - 14px) / ${labels.length})`,borderRadius:14,background:done?`${primary}30`:"rgba(255,255,255,.12)",border:`1px solid ${done?primary:"rgba(255,255,255,.16)"}`,boxShadow:`0 8px 22px rgba(0,0,0,.2),0 0 ${done*18}px ${primary}24`,transform:`translateX(${focusPos*100}%)`}}/>{labels.map((label,i)=><div key={label} style={{flex:1,padding:"20px 12px",textAlign:"center",font:`${i===selected&&done>.4?700:500} 16px ${fonts.sans}`,color:i===selected&&done>.4?"white":"rgba(255,255,255,.48)",zIndex:1,transform:`translateY(${i===selected?-done*2:0}px)`}}>{label}</div>)}</div></div><div style={{position:"absolute",left:"50%",top:"77%",font:`12px ${fonts.mono}`,letterSpacing:".13em",color:primary,opacity:done,transform:`translate(-50%,${(1-done)*12}px)`}}>MODE TERPILIH · {labels[selected]}</div></>;
};

const DataTitle:React.FC<{title:string;subtitle?:string;primary:string;frame:number;duration:number;tag:string}> = ({title,subtitle,primary,frame,duration,tag}) => {const p=at(frame,duration,.02,.17);const s=at(frame,duration,.12,.27);return <div style={{position:"absolute",left:78,top:60,right:78,display:"flex",justifyContent:"space-between",alignItems:"flex-end"}}><div><Eyebrow progress={p} color={`${primary}c8`}>{tag}</Eyebrow><div style={{font:`700 43px/1.05 ${fonts.display}`,letterSpacing:"-.045em",marginTop:11,opacity:p}}>{title}</div></div><div style={{font:`15px/1.5 ${fonts.sans}`,color:"rgba(255,255,255,.45)",width:390,textAlign:"right",opacity:s}}>{subtitle}</div></div>};

const Metric:React.FC<{title:string;subtitle?:string;value:string|number;secondary:string|number;primary:string;frame:number;duration:number;icon?:LucideIconName}> = ({title,subtitle,value,secondary,primary,frame,duration,icon}) => {
  const shell=at(frame,duration,.18,.32); const gauge=at(frame,duration,.3,.68,Easing.inOut(Easing.cubic)); const overshoot=at(frame,duration,.55,.68,tactileEase); const settle=at(frame,duration,.68,.76); const status=at(frame,duration,.73,.86); const raw=String(value); const m=raw.match(/^([^\d-]*)(-?\d+(?:[.,]\d+)?)(.*)$/); const target=m?Number(m[2].replace(",",".")):0; const decimals=m?.[2].match(/[.,](\d+)/)?.[1].length??0; const count=settle<1?target*gauge+(Math.sin(overshoot*Math.PI)*Math.max(1,target*.055)):(target); const shown=m?`${m[1]}${count.toFixed(decimals).replace(".",m[2].includes(",")?",":".")}${m[3]}`:raw; const arc=220*gauge;
  return <><LightField primary={primary} frame={frame} duration={duration} focus={[64,60]} payoff={status}/><DataTitle title={title} subtitle={subtitle} primary={primary} frame={frame} duration={duration} tag="TELEMETRI · LANGSUNG"/><div style={{position:"absolute",left:"50%",top:"61%",width:760,height:350,transform:"translate(-50%,-50%)",...glass,borderRadius:42,opacity:shell,overflow:"hidden"}}><svg viewBox="0 0 360 300" style={{position:"absolute",left:25,top:18,width:350,height:300,overflow:"visible"}}><path d="M55 235 A135 135 0 1 1 305 235" pathLength="220" fill="none" stroke="rgba(255,255,255,.08)" strokeWidth="16" strokeLinecap="round"/><path d="M55 235 A135 135 0 1 1 305 235" pathLength="220" fill="none" stroke={primary} strokeWidth="16" strokeLinecap="round" strokeDasharray="220" strokeDashoffset={220-arc} style={{filter:`drop-shadow(0 0 ${status*10}px ${primary})`}}/></svg><IconBox icon={icon} primary={primary} size={39} progress={gauge} rotate={-35+gauge*70} style={{position:"absolute",left:177,top:114,width:52,height:52,transformOrigin:"50% 122px"}}/><div style={{position:"absolute",left:402,top:74}}><Eyebrow progress={shell}>NILAI SAAT INI</Eyebrow><div style={{font:`800 96px ${fonts.display}`,fontVariantNumeric:"tabular-nums",letterSpacing:"-.075em",marginTop:10,transform:`scale(${.96+Math.sin(overshoot*Math.PI)*.04})`,transformOrigin:"left"}}>{shown}</div><div style={{display:"inline-flex",gap:9,alignItems:"center",padding:"9px 13px",borderRadius:999,background:`${primary}16`,color:primary,font:`700 14px ${fonts.mono}`,opacity:status,transform:`translateY(${(1-status)*12}px)`}}>↗ {secondary}</div></div></div></>;
};

const LineChart:React.FC<{title:string;subtitle?:string;value:string|number;labels:string[];primary:string;frame:number;duration:number;icon?:LucideIconName}> = ({title,subtitle,value,labels,primary,frame,duration,icon}) => {
  const shell=at(frame,duration,.16,.29); const iconIn=at(frame,duration,.23,.36); const first=at(frame,duration,.33,.55,Easing.inOut(Easing.cubic)); const pause=at(frame,duration,.55,.62); const finish=at(frame,duration,.62,.78,Easing.inOut(Easing.cubic)); const callout=at(frame,duration,.76,.88,tactileEase); const draw=first*.56+finish*.44; const path="M 32 225 C 105 220,120 188,190 194 C 245 200,265 142,325 150 C 365 156,395 96,455 111 C 512 124,535 57,604 68 C 660 76,704 29,770 38";
  return <><LightField primary={primary} frame={frame} duration={duration} focus={[65,61]} payoff={callout}/><DataTitle title={title} subtitle={subtitle} primary={primary} frame={frame} duration={duration} tag="ANALISIS · TREN"/><div style={{position:"absolute",left:"50%",top:"62%",width:980,height:400,transform:"translate(-50%,-50%)",...glass,borderRadius:38,opacity:shell,padding:"28px 42px",boxSizing:"border-box"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div style={{display:"flex",alignItems:"center",gap:13}}><IconBox icon={icon} primary={primary} size={30} progress={iconIn} style={{width:44,height:44,borderRadius:15,background:`${primary}14`}}/><b style={{font:`700 20px ${fonts.mono}`,letterSpacing:".04em"}}>{value}</b></div><span style={{font:`700 13px ${fonts.mono}`,color:primary,opacity:callout}}>PERTUMBUHAN +24,8%</span></div><svg viewBox="0 0 800 270" style={{width:"100%",height:270,overflow:"visible",marginTop:5}}>{[55,120,185,250].map((y,i)=><line key={y} x1="25" x2="780" y1={y} y2={y} stroke="rgba(255,255,255,.07)" opacity={at(frame,duration,.24+i*.025,.4+i*.025)}/>)}<path d={path} pathLength="1" fill="none" stroke={primary} strokeWidth="7" strokeLinecap="round" strokeDasharray="1" strokeDashoffset={1-draw} style={{filter:`drop-shadow(0 0 ${callout*9}px ${primary})`}}/><circle cx="325" cy="150" r={5+pause*3} fill="#050506" stroke={primary} strokeWidth="4" opacity={pause}/><circle cx="770" cy="38" r={6+Math.sin(callout*Math.PI)*5} fill="#fff" stroke={primary} strokeWidth="5" opacity={callout}/><g opacity={callout} transform={`translate(${(1-callout)*18} 0)`}><rect x="616" y="-18" width="132" height="42" rx="13" fill="#111216" stroke={`${primary}88`}/><text x="682" y="8" textAnchor="middle" fill="#fff" fontFamily={fonts.mono} fontSize="12">PUNCAK EKSPOR</text></g></svg><div style={{display:"flex",justifyContent:"space-between",font:`11px ${fonts.mono}`,color:"rgba(255,255,255,.34)",padding:"0 18px"}}>{(labels.length?labels:["MULAI","PROSES","HASIL"]).map(x=><span key={x}>{x}</span>)}</div></div></>;
};

const Comparison:React.FC<{title:string;subtitle?:string;items:AppleMotionItem[];primary:string;frame:number;duration:number;icon?:LucideIconName}> = ({title,subtitle,items,primary,frame,duration,icon}) => {
  const shell=at(frame,duration,.17,.3); const before=at(frame,duration,.25,.42); const sweep=at(frame,duration,.43,.66,mechanicalEase); const settle=at(frame,duration,.64,.75,tactileEase); const payoff=at(frame,duration,.72,.86); const left=items[0]??{label:"Sebelum",value:"92%"}; const right=items[1]??{label:"Sesudah",value:"37%"};
  return <><LightField primary={primary} frame={frame} duration={duration} focus={[58,61]} payoff={payoff}/><DataTitle title={title} subtitle={subtitle} primary={primary} frame={frame} duration={duration} tag="PERBANDINGAN · DAMPAK"/><div style={{position:"absolute",left:"50%",top:"62%",width:930,height:365,transform:"translate(-50%,-50%)",...glass,borderRadius:38,overflow:"hidden",opacity:shell}}><div style={{position:"absolute",inset:0,display:"grid",gridTemplateColumns:`${50-sweep*12}% ${50+sweep*12}%`}}><div style={{padding:"54px 48px",filter:`saturate(${1-sweep*.72})`,opacity:.72+.28*before}}><Eyebrow progress={before}>SEBELUM</Eyebrow><div style={{font:`700 25px ${fonts.sans}`,marginTop:22}}>{left.label}</div><div style={{font:`800 82px ${fonts.display}`,letterSpacing:"-.07em",marginTop:10}}>{left.value??"92%"}</div><svg viewBox="0 0 280 55" style={{width:260,marginTop:22}}><path d="M0 28 C25 4,42 51,68 25 S110 8,135 31 S176 52,204 20 S246 4,280 29" fill="none" stroke="rgba(255,255,255,.25)" strokeWidth="4"/></svg></div><div style={{padding:"54px 48px",background:`linear-gradient(110deg,${primary}08,${primary}1c)`,transform:`translateX(${(1-settle)*26}px)`}}><Eyebrow color={primary} progress={settle}>SESUDAH</Eyebrow><div style={{font:`700 25px ${fonts.sans}`,marginTop:22}}>{right.label}</div><div style={{font:`800 82px ${fonts.display}`,letterSpacing:"-.07em",marginTop:10,color:"#fff"}}>{right.value??"37%"}</div><div style={{display:"flex",alignItems:"center",gap:12,marginTop:21,opacity:payoff}}><IconBox icon={icon} primary={primary} size={27}/><svg viewBox="0 0 235 48" style={{width:235}}><path d="M0 25 C28 22,43 27,67 24 S110 23,135 25 S178 24,205 25 S222 25,235 25" fill="none" stroke={primary} strokeWidth="4" strokeDasharray="235" strokeDashoffset={235-payoff*235}/></svg></div></div></div><div style={{position:"absolute",left:`${50-sweep*12}%`,top:0,bottom:0,width:2,background:`linear-gradient(transparent,${primary},transparent)`,boxShadow:`0 0 ${payoff*18}px ${primary}`,transform:`translateX(${Math.sin(settle*Math.PI)*5}px)`}}/></div></>;
};

const nodeIcons:LucideIconName[]=["workflow","panels-top-left","microchip","monitor"];
const DataFlow:React.FC<{title:string;subtitle?:string;items:AppleMotionItem[];primary:string;frame:number;duration:number;icon?:LucideIconName}> = ({title,subtitle,items,primary,frame,duration,icon}) => {
  const shown=items.slice(0,4); const complete=at(frame,duration,.78,.9); return <><LightField primary={primary} frame={frame} duration={duration} focus={[58,61]} payoff={complete}/><DataTitle title={title} subtitle={subtitle} primary={primary} frame={frame} duration={duration} tag="ALUR · SISTEM"/><div style={{position:"absolute",left:"50%",top:"62%",width:1020,transform:"translate(-50%,-50%)",display:"flex",alignItems:"center"}}>{shown.map((item,i)=>{const start=.18+i*.15;const node=at(frame,duration,start,start+.1,tactileEase);const active=at(frame,duration,start+.1,start+.18);const packet=i<shown.length-1?at(frame,duration,start+.13,start+.28,mechanicalEase):0;const semantic=i===2&&icon?icon:nodeIcons[i];return <React.Fragment key={item.label}><div style={{...glass,width:165,height:160,borderRadius:i===3?34:48,display:"grid",placeItems:"center",textAlign:"center",opacity:node,transform:`scale(${.82+node*.18+Math.sin(active*Math.PI)*.035})`,border:`1px solid ${active>.4?primary:"rgba(255,255,255,.14)"}`,boxShadow:`0 24px 55px rgba(0,0,0,.26),0 0 ${active*22}px ${primary}28`}}><div><IconBox icon={semantic} primary={active>.3?primary:"rgba(255,255,255,.65)"} size={38} progress={node} style={{margin:"0 auto 18px"}}/><div style={{font:`700 16px ${fonts.sans}`}}>{item.label}</div><div style={{font:`10px ${fonts.mono}`,letterSpacing:".12em",color:active>.5?primary:"rgba(255,255,255,.3)",marginTop:9}}>{active>.6?"AKTIF":"MENUNGGU"}</div></div></div>{i<shown.length-1&&<div style={{height:28,flex:1,position:"relative",overflow:"hidden"}}><div style={{position:"absolute",left:0,right:0,top:13,height:2,background:"rgba(255,255,255,.1)"}}/><div style={{position:"absolute",left:0,top:13,width:`${packet*100}%`,height:2,background:primary,boxShadow:`0 0 10px ${primary}`}}/><div style={{position:"absolute",left:`${packet*100}%`,top:8,width:12,height:12,borderRadius:"50%",background:"white",boxShadow:`0 0 13px ${primary}`,opacity:packet*(1-at(frame,duration,start+.27,start+.29))}}/></div>}</React.Fragment>})}</div><div style={{position:"absolute",left:"50%",bottom:55,transform:"translateX(-50%)",font:`700 12px ${fonts.mono}`,letterSpacing:".13em",color:primary,opacity:complete}}>ALUR SELESAI · HASIL SIAP</div></>;
};

const Table:React.FC<{title:string;subtitle?:string;items:AppleMotionItem[];labels:string[];primary:string;frame:number;duration:number;icon?:LucideIconName}> = ({title,subtitle,items,labels,primary,frame,duration,icon}) => {
  const shell=at(frame,duration,.15,.28); const grid=at(frame,duration,.25,.45,mechanicalEase); const scan=at(frame,duration,.43,.74,Easing.linear); const validate=at(frame,duration,.67,.82); return <><LightField primary={primary} frame={frame} duration={duration} focus={[63,62]} payoff={validate}/><DataTitle title={title} subtitle={subtitle} primary={primary} frame={frame} duration={duration} tag="AUDIT · PERANGKAT"/><div style={{position:"absolute",left:"50%",top:"62%",width:960,transform:"translate(-50%,-50%)",...glass,borderRadius:34,overflow:"hidden",opacity:shell}}><div style={{height:54,display:"flex",alignItems:"center",gap:13,padding:"0 25px",borderBottom:"1px solid rgba(255,255,255,.09)"}}><IconBox icon={icon} primary={primary} size={25} progress={grid} rotate={(1-grid)*-25}/><span style={{font:`700 11px ${fonts.mono}`,letterSpacing:".14em",color:"rgba(255,255,255,.46)"}}>TABEL KONFIGURASI</span></div><div style={{position:"relative",clipPath:`inset(0 ${100-grid*100}% 0 0)`}}><div style={{display:"grid",gridTemplateColumns:"1.5fr 1fr 1fr",padding:"16px 28px",font:`700 11px ${fonts.mono}`,letterSpacing:".12em",color:"rgba(255,255,255,.34)"}}>{(labels.length?labels:["NAMA","NILAI","STATUS"]).slice(0,3).map(x=><span key={x}>{x}</span>)}</div>{items.slice(0,5).map((item,i)=>{const row=at(frame,duration,.34+i*.055,.43+i*.055);const checked=at(frame,duration,.67+i*.035,.75+i*.035);return <div key={item.label} style={{display:"grid",gridTemplateColumns:"1.5fr 1fr 1fr",padding:"17px 28px",borderTop:"1px solid rgba(255,255,255,.075)",font:`15px ${fonts.sans}`,opacity:row,transform:`translateX(${(1-row)*18}px)`}}><b>{item.label}</b><span style={{color:"rgba(255,255,255,.62)"}}>{item.value??`${88-i*7}%`}</span><span style={{display:"flex",gap:9,alignItems:"center",color:checked?item.color??primary:"rgba(255,255,255,.35)"}}><span style={{width:16,height:16,borderRadius:5,border:`1px solid ${checked?item.color??primary:"rgba(255,255,255,.22)"}`,display:"grid",placeItems:"center",fontSize:11,transform:`scale(${.8+checked*.2})`}}>{checked>.55?"✓":""}</span>{item.detail??"Aktif"}</span></div>})}<div style={{position:"absolute",left:0,right:0,top:`${scan*100}%`,height:2,background:`linear-gradient(90deg,transparent,${primary},transparent)`,boxShadow:`0 0 16px ${primary}`,opacity:scan*(1-validate)}}/></div></div></>;
};

const ScreenWindow:React.FC<{title:string;subtitle?:string;primary:string;frame:number;duration:number;icon?:LucideIconName}> = ({title,subtitle,primary,frame,duration,icon}) => {
  const iconIn=at(frame,duration,.03,.16); const expand=at(frame,duration,.13,.4,tactileEase); const ui=at(frame,duration,.36,.52); const cursor=at(frame,duration,.5,.66,mechanicalEase); const select=at(frame,duration,.65,.76,tactileEase); const x=mix(720,580,cursor); const y=mix(330,230,cursor);
  return <><LightField primary={primary} frame={frame} duration={duration} focus={[52,53]} payoff={select}/><div style={{position:"absolute",left:74,top:76,zIndex:3}}><Eyebrow progress={iconIn} color={`${primary}cc`}>TAMPILAN · PENGATURAN</Eyebrow><div style={{font:`400 55px ${fonts.classic}`,marginTop:12,opacity:ui}}>{title}</div><div style={{font:`16px ${fonts.sans}`,color:"rgba(255,255,255,.45)",marginTop:8,opacity:ui}}>{subtitle}</div></div><div style={{position:"absolute",left:"50%",top:"57%",width:900,height:470,transform:`translate(-50%,-50%) scale(${.18+expand*.82}) rotateX(${(1-expand)*12}deg) rotateY(${(1-expand)*-15}deg)`,transformOrigin:"50% 50%",...glass,borderRadius:32,overflow:"hidden",opacity:iconIn,perspective:1000}}><IconBox icon={icon} primary={primary} size={130} progress={1-ui} style={{position:"absolute",inset:0}}/><div style={{opacity:ui}}><div style={{height:52,borderBottom:"1px solid rgba(255,255,255,.1)",display:"flex",alignItems:"center",padding:"0 20px",gap:8}}>{["#ff5f57","#febc2e","#28c840"].map(c=><i key={c} style={{width:11,height:11,borderRadius:"50%",background:c}}/>)}<span style={{margin:"auto",font:`12px ${fonts.mono}`,color:"rgba(255,255,255,.4)"}}>PENGATURAN GRAFIS</span></div><div style={{display:"grid",gridTemplateColumns:".65fr 1.35fr",height:418}}><aside style={{borderRight:"1px solid rgba(255,255,255,.08)",padding:28}}>{["Sistem","Layar","Grafis","Tentang"].map((x,i)=><div key={x} style={{padding:"12px 14px",borderRadius:10,background:i===2?`${primary}18`:"transparent",color:i===2?"white":"rgba(255,255,255,.38)",font:`14px ${fonts.sans}`,marginBottom:5}}>{x}</div>)}</aside><main style={{padding:34}}><Eyebrow>Aplikasi aktif</Eyebrow><div style={{font:`700 25px ${fonts.display}`,marginTop:12}}>Preferensi performa grafis</div>{["Hemat daya · Grafis bawaan","Performa tinggi · GPU dedicated"].map((label,i)=><div key={label} style={{marginTop:24,padding:"18px 20px",borderRadius:16,border:`1px solid ${i===1&&select>.3?primary:"rgba(255,255,255,.11)"}`,background:i===1?`${primary}${select>.3?"20":"08"}`:"rgba(255,255,255,.025)",font:`15px ${fonts.sans}`,transform:`scale(${i===1?1+Math.sin(select*Math.PI)*.018:1})`}}>{label}{i===1&&<span style={{float:"right",color:primary,opacity:select}}>✓ Dipilih</span>}</div>)}</main></div></div>{icon&&<div style={{position:"absolute",left:x,top:y,opacity:ui,transform:`scale(${1-select*.12})`,filter:"drop-shadow(0 5px 5px #0008)"}}><LucideIcon name="mouse-pointer-click" size={38} color="#fff"/></div>}</div></>;
};

const PresenterGraphic:React.FC<{title:string;subtitle?:string;primary:string;frame:number;duration:number;icon?:LucideIconName}> = ({title,subtitle,primary,frame,duration,icon}) => {
  const portrait=at(frame,duration,.04,.26); const rim=at(frame,duration,.16,.38); const card=at(frame,duration,.25,.5,tactileEase); const pointer=at(frame,duration,.48,.64); const copy=at(frame,duration,.57,.75); return <><LightField primary={primary} frame={frame} duration={duration} focus={[34,56]} payoff={copy}/><div style={{position:"absolute",left:90,bottom:0,width:430,height:570,opacity:portrait,transform:`translateX(${(1-portrait)*-60}px)`}}><div style={{position:"absolute",left:30,top:45,width:300,height:300,borderRadius:"48% 52% 44% 46%",background:`radial-gradient(circle at 48% 31%,#f1c4a9 0 22%,#242128 23% 44%,${primary} 45% 70%,#111218 71%)`,boxShadow:`-16px 20px 0 ${primary}18,0 40px 70px rgba(0,0,0,.38)`,transform:`translateY(${Math.sin(frame/32)*3}px)`}}/><div style={{position:"absolute",left:2,top:25,width:350,height:350,borderRadius:"50%",border:`1px solid ${primary}70`,opacity:rim,clipPath:"inset(0 0 0 50%)"}}/><div style={{position:"absolute",left:34,bottom:65}}><Eyebrow progress={rim} color={primary}>PRESENTER · UTAMA</Eyebrow><div style={{font:`400 30px ${fonts.playfair}`,marginTop:9,opacity:rim}}>Penjelasan yang meyakinkan</div></div></div><div style={{position:"absolute",right:82,top:155,width:665,padding:"48px 52px",...glass,borderRadius:36,opacity:card,transform:`translateX(${(1-card)*85}px) rotateY(${(1-card)*-8}deg)`}}><Eyebrow progress={card}>INTI PEMBAHASAN</Eyebrow><div style={{font:`400 54px/1.04 ${fonts.classic}`,marginTop:19}}>{title}</div><div style={{font:`700 21px/1.45 ${fonts.displayItalic}`,color:primary,marginTop:18,opacity:copy}}>{subtitle}</div><div style={{height:1,background:"rgba(255,255,255,.12)",margin:"30px 0 22px",transform:`scaleX(${copy})`,transformOrigin:"left"}}/><div style={{font:`15px/1.55 ${fonts.sans}`,color:"rgba(255,255,255,.45)",opacity:copy}}>Informasi utama hadir berdampingan dengan presenter, tetap jelas tanpa kehilangan hubungan personal.</div></div><div style={{position:"absolute",left:438,top:318,width:130,height:2,background:`linear-gradient(90deg,${primary},transparent)`,transform:`scaleX(${pointer}) rotate(-8deg)`,transformOrigin:"left",boxShadow:`0 0 9px ${primary}`}}/><IconBox icon={icon} primary={primary} size={31} progress={pointer} rotate={(1-pointer)*-20} style={{position:"absolute",left:424,top:292,width:54,height:54,borderRadius:18,background:"#101114",border:`1px solid ${primary}66`}}/></>;
};

const BigStatement:React.FC<{title:string;subtitle?:string;primary:string;frame:number;duration:number;icon?:LucideIconName}> = ({title,subtitle,primary,frame,duration,icon}) => {
  const charge=at(frame,duration,.02,.22,Easing.in(Easing.cubic)); const flash=at(frame,duration,.22,.34,tactileEase); const words=title.split(" "); const first=at(frame,duration,.13,.3,editorialEase); const second=at(frame,duration,.29,.46,tactileEase); const settle=at(frame,duration,.45,.58); const sub=at(frame,duration,.52,.7); const lineWidth=charge*220;
  return <><LightField primary={primary} frame={frame} duration={duration} focus={[50,48]} payoff={flash*(1-settle)}/><div style={{position:"absolute",left:"50%",top:82,transform:"translateX(-50%)",display:"flex",alignItems:"center",gap:12}}><div style={{width:lineWidth,height:1,background:`linear-gradient(90deg,transparent,${primary})`}}/><IconBox icon={icon} primary={flash>.35?"#fff":primary} size={44} progress={charge} rotate={-16+flash*16} style={{width:70,height:70,borderRadius:24,border:`1px solid ${primary}60`,background:`${primary}${charge>.7?"24":"0e"}`,boxShadow:`0 0 ${charge*28}px ${primary}48`}}/><div style={{width:lineWidth,height:1,background:`linear-gradient(90deg,${primary},transparent)`}}/></div><div style={{position:"absolute",left:0,right:0,top:"47%",height:2,background:"white",opacity:flash*(1-settle),boxShadow:`0 0 32px 12px ${primary}`,transform:`scaleX(${flash})`}}/><div style={{position:"absolute",left:"50%",top:"52%",width:"94%",transform:`translate(-50%,-50%)`,textAlign:"center"}}><div style={{font:`800 ${words.length>2?108:142}px/.82 ${fonts.display}`,letterSpacing:"-.085em",textTransform:"uppercase"}}>{words.map((word,i)=>{const p=i===0?first:second;const hierarchy=i===0?.62:1;return <span key={`${word}-${i}`} style={{display:"inline-block",margin:"0 .08em",opacity:p,transform:`translateY(${(1-p)*(i===0?55:-55)}px) scale(${hierarchy*(.84+p*.16)+Math.sin(p*Math.PI)*.045})`,color:i===0?"rgba(255,255,255,.55)":"#fff",fontFamily:i===0?fonts.mono:fonts.display,fontStyle:i===words.length-1?"italic":"normal",textShadow:i?`0 14px ${settle*28}px ${primary}40`:undefined}}>{word}</span>})}</div><div style={{font:`700 18px ${fonts.displayItalic}`,color:primary,marginTop:42,opacity:sub,transform:`translateY(${(1-sub)*18}px)`,letterSpacing:".01em"}}>{subtitle}</div></div></>;
};

const ProcessNetwork:React.FC<{title:string;subtitle?:string;items:AppleMotionItem[];primary:string;frame:number;duration:number;icon?:LucideIconName}> = ({title,subtitle,items,primary,frame,duration,icon}) => {
  const nodes=items.slice(0,6); const blueprint=at(frame,duration,.04,.18); const expand=at(frame,duration,.15,.36,tactileEase); const result=at(frame,duration,.76,.9); const coords:[[number,number],[number,number],[number,number],[number,number],[number,number],[number,number]]=[[450,205],[105,75],[450,55],[795,75],[245,350],[655,350]]; const routeIcons:LucideIconName[]=[icon??"network","workflow","cpu","microchip","route","monitor"];
  return <><LightField primary={primary} frame={frame} duration={duration} focus={[50,59]} payoff={result}/><DataTitle title={title} subtitle={subtitle} primary={primary} frame={frame} duration={duration} tag="ORKESTRASI · JARINGAN"/><div style={{position:"absolute",left:"50%",top:"63%",width:900,height:410,transform:"translate(-50%,-50%)"}}><svg viewBox="0 0 900 410" style={{position:"absolute",inset:0,overflow:"visible"}}>{coords.slice(1).map(([x,y],i)=>{const line=at(frame,duration,.28+i*.035,.48+i*.035);const packet=at(frame,duration,.48+i*.045,.68+i*.045,mechanicalEase);const sx=450,sy=205;const px=sx+(x-sx)*packet,py=sy+(y-sy)*packet;return <g key={i}><line x1={sx} y1={sy} x2={x} y2={y} stroke="rgba(255,255,255,.09)" strokeWidth="2"/><line x1={sx} y1={sy} x2={x} y2={y} stroke={primary} strokeWidth="2" pathLength="1" strokeDasharray="1" strokeDashoffset={1-line}/><circle cx={px} cy={py} r="6" fill="#fff" opacity={packet*(1-at(frame,duration,.67+i*.045,.71+i*.045))} style={{filter:`drop-shadow(0 0 8px ${primary})`}}/></g>})}</svg>{nodes.map((item,i)=>{const center=i===0;const [x,y]=coords[i];const p=center?expand:at(frame,duration,.3+(i-1)*.035,.45+(i-1)*.035,tactileEase);const active=center?blueprint:at(frame,duration,.65+(i-1)*.045,.72+(i-1)*.045);return <div key={item.label} style={{position:"absolute",left:x-(center?72:54),top:y-(center?72:54),width:center?144:108,height:center?144:108,borderRadius:center?44:"50%",...glass,display:"grid",placeItems:"center",textAlign:"center",opacity:p,transform:`scale(${.72+p*.28+Math.sin(active*Math.PI)*.04})`,border:`1px solid ${active>.35?primary:"rgba(255,255,255,.13)"}`,boxShadow:`0 20px 45px rgba(0,0,0,.26),0 0 ${active*22}px ${primary}26`}}><div><IconBox icon={routeIcons[i]} primary={active>.3?primary:"rgba(255,255,255,.62)"} size={center?38:25} progress={p} style={{margin:"0 auto 9px"}}/><span style={{font:`700 ${center?15:12}px ${fonts.sans}`}}>{item.label}</span></div></div>})}</div><div style={{position:"absolute",left:"50%",bottom:35,transform:"translateX(-50%)",display:"flex",alignItems:"center",gap:10,font:`700 11px ${fonts.mono}`,letterSpacing:".13em",color:primary,opacity:result}}><LucideIcon name="list-checks" size={20} color={primary}/>SEMUA SISTEM TERHUBUNG</div></>;
};

const SummarySteps:React.FC<{title:string;subtitle?:string;items:AppleMotionItem[];primary:string;frame:number;duration:number;icon?:LucideIconName}> = ({title,subtitle,items,primary,frame,duration,icon}) => {
  const shown=items.slice(0,3); const final=at(frame,duration,.77,.9,tactileEase); const icons:LucideIconName[]=["workflow","gauge","monitor"]; return <><LightField primary={primary} frame={frame} duration={duration} focus={[58,59]} payoff={final}/><div style={{position:"absolute",left:78,top:65,right:78,display:"flex",alignItems:"flex-start",justifyContent:"space-between"}}><div><Eyebrow progress={at(frame,duration,.02,.16)} color={`${primary}c8`}>RINGKASAN · TIGA LANGKAH</Eyebrow><div style={{font:`700 49px ${fonts.display}`,letterSpacing:"-.05em",marginTop:12}}>{title}</div></div><div style={{font:`700 16px/1.45 ${fonts.displayItalic}`,color:"rgba(255,255,255,.48)",width:390,textAlign:"right",opacity:at(frame,duration,.1,.24)}}>{subtitle}</div></div><div style={{position:"absolute",left:"50%",top:"59%",width:1050,transform:"translate(-50%,-50%)",display:"flex",alignItems:"center"}}>{shown.map((item,i)=>{const start=.18+i*.18;const p=at(frame,duration,start,start+.12,tactileEase);const complete=at(frame,duration,start+.11,start+.2);return <React.Fragment key={item.label}><div style={{width:260,minHeight:225,padding:"29px 28px",boxSizing:"border-box",borderRadius:30,...glass,opacity:p,transform:`translateY(${(1-p)*32}px) scale(${.94+p*.06})`,border:`1px solid ${complete>.5?primary:"rgba(255,255,255,.13)"}`}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><IconBox icon={icons[i]} primary={complete>.3?primary:"rgba(255,255,255,.55)"} size={30} progress={p}/><span style={{font:`700 24px ${fonts.mono}`,color:"rgba(255,255,255,.22)"}}>0{i+1}</span></div><div style={{font:`700 18px/1.25 ${fonts.sans}`,marginTop:26}}>{item.label}</div><div style={{font:`13px/1.45 ${fonts.sans}`,color:"rgba(255,255,255,.42)",marginTop:10}}>{item.detail}</div><div style={{marginTop:22,font:`700 10px ${fonts.mono}`,letterSpacing:".12em",color:primary,opacity:complete}}>✓ SELESAI</div></div>{i<shown.length-1&&<div style={{width:125,height:2,background:"rgba(255,255,255,.09)",position:"relative"}}><div style={{height:2,width:`${at(frame,duration,start+.17,start+.28)*100}%`,background:primary,boxShadow:`0 0 10px ${primary}`}}/><div style={{position:"absolute",right:-1,top:-4,width:10,height:10,borderTop:`2px solid ${primary}`,borderRight:`2px solid ${primary}`,transform:"rotate(45deg)",opacity:at(frame,duration,start+.24,start+.28)}}/></div>}</React.Fragment>})}</div><div style={{position:"absolute",left:"50%",bottom:35,transform:`translateX(-50%) scale(${.86+final*.14})`,display:"flex",alignItems:"center",gap:12,padding:"12px 20px",borderRadius:999,background:`${primary}16`,border:`1px solid ${primary}70`,font:`700 12px ${fonts.mono}`,letterSpacing:".12em",color:primary,opacity:final}}><LucideIcon name={icon??"list-checks"} size={24} color={primary}/>SEMUA LANGKAH TUNTAS</div></>;
};

export const AppleMotion:React.FC<AppleMotionProps> = ({variant,title="Dirancang untuk langkah berikutnya.",subtitle="Ide kuat yang disampaikan dengan jelas.",primary=BLUE,background,value="Lanjutkan",secondaryValue="+18,4%",labels=[],items,icon,audioEnabled=false}) => {
  const frame=useCurrentFrame(); const {width,height,durationInFrames}=useVideoConfig(); const duration=Math.max(1,durationInFrames); const isLight=variant===AppleMotionVariant.LightStage; const bg=background??(isLight?LIGHT:DARK); const normalized=normalizeItems(items,["Temukan","Rancang","Bangun","Sempurnakan","Kirim","Kembangkan"]); const selectedIcon=icon==="none"?undefined:(icon??variantIcon[variant]); const scale=Math.min(width/1280,height/720); let content:ReactNode;
  switch(variant){
    case AppleMotionVariant.DarkStage:content=<DarkStage title={title} subtitle={subtitle} primary={primary} frame={frame} duration={duration} icon={selectedIcon}/>;break;
    case AppleMotionVariant.LightStage:content=<LightStage title={title} subtitle={subtitle} primary={primary} frame={frame} duration={duration} icon={selectedIcon}/>;break;
    case AppleMotionVariant.GlassButton:content=<GlassButton title={title} subtitle={subtitle} value={value} primary={primary} frame={frame} duration={duration} icon={selectedIcon}/>;break;
    case AppleMotionVariant.Toggle:content=<Toggle title={title} subtitle={subtitle} primary={primary} frame={frame} duration={duration} icon={selectedIcon}/>;break;
    case AppleMotionVariant.SegmentControl:content=<SegmentControl title={title} subtitle={subtitle} value={value} labels={labels.length?labels:["Otomatis","Hemat Daya","Performa Tinggi"]} primary={primary} frame={frame} duration={duration} icon={selectedIcon}/>;break;
    case AppleMotionVariant.Metric:content=<Metric title={title} subtitle={subtitle} value={value} secondary={secondaryValue} primary={primary} frame={frame} duration={duration} icon={selectedIcon}/>;break;
    case AppleMotionVariant.LineChart:content=<LineChart title={title} subtitle={subtitle} value={value} labels={labels} primary={primary} frame={frame} duration={duration} icon={selectedIcon}/>;break;
    case AppleMotionVariant.Comparison:content=<Comparison title={title} subtitle={subtitle} items={normalized} primary={primary} frame={frame} duration={duration} icon={selectedIcon}/>;break;
    case AppleMotionVariant.DataFlow:content=<DataFlow title={title} subtitle={subtitle} items={normalized} primary={primary} frame={frame} duration={duration} icon={selectedIcon}/>;break;
    case AppleMotionVariant.Table:content=<Table title={title} subtitle={subtitle} items={normalized} labels={labels} primary={primary} frame={frame} duration={duration} icon={selectedIcon}/>;break;
    case AppleMotionVariant.ScreenWindow:content=<ScreenWindow title={title} subtitle={subtitle} primary={primary} frame={frame} duration={duration} icon={selectedIcon}/>;break;
    case AppleMotionVariant.PresenterGraphic:content=<PresenterGraphic title={title} subtitle={subtitle} primary={primary} frame={frame} duration={duration} icon={selectedIcon}/>;break;
    case AppleMotionVariant.BigStatement:content=<BigStatement title={title} subtitle={subtitle} primary={primary} frame={frame} duration={duration} icon={selectedIcon}/>;break;
    case AppleMotionVariant.ProcessNetwork:content=<ProcessNetwork title={title} subtitle={subtitle} items={normalized} primary={primary} frame={frame} duration={duration} icon={selectedIcon}/>;break;
    case AppleMotionVariant.SummarySteps:content=<SummarySteps title={title} subtitle={subtitle} items={normalized} primary={primary} frame={frame} duration={duration} icon={selectedIcon}/>;break;
    default:content=null;
  }
  return <AbsoluteFill style={{background:bg,overflow:"hidden",color:isLight?"#1d1d1f":"#f5f5f7"}}><AudioCues enabled={audioEnabled} variant={variant} duration={duration}/><div style={{position:"absolute",left:"50%",top:"50%",width:1280,height:720,transform:`translate(-50%,-50%) scale(${scale})`,overflow:"hidden"}}>{content}</div></AbsoluteFill>;
};
