// api/server.mjs
// ============================================================
// Express backend. Terima form dari UI, generate preset JSON,
// panggil Remotion render, balikin URL MP4.
// ============================================================

import express from "express";
import cors from "cors";
import { spawn } from "node:child_process";
import { writeFileSync, existsSync, mkdirSync, readFileSync, readdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const PRESETS_DIR = join(ROOT, "presets");
const TMP_CONFIG = join(ROOT, "src", "_config.generated.ts");
const OUT_DIR = join(ROOT, "out");

const app = express();
app.use(cors());
app.use(express.json({ limit: "2mb" }));

// Serve static MP4 from out/
app.use("/out", express.static(OUT_DIR));

// ─── POST /render ───
// Body: { style, name, lines, audio: { sfxEnabled, padEnabled, sfxVolume, padVolume } }
app.post("/render", async (req, res) => {
  const { style, name, lines, audio } = req.body || {};

  if (!style) return res.status(400).json({ error: "style required" });
  if (!Array.isArray(lines) || lines.length === 0) {
    return res.status(400).json({ error: "lines array required" });
  }

  // Load base preset
  const presetPath = join(PRESETS_DIR, `${style}.json`);
  if (!existsSync(presetPath)) {
    return res.status(400).json({ error: `unknown style: ${style}` });
  }
  const preset = JSON.parse(
    await import("node:fs").then(fs => fs.readFileSync(presetPath, "utf8"))
  );

  // Apply line overrides
  // lines[].index = which element to override (0-based)
  for (const ln of lines) {
    const idx = ln.index;
    if (typeof idx !== "number") continue;
    const el = preset.elements[idx];
    if (!el) continue;
    if (typeof ln.text === "string") el.text = ln.text;
    if (typeof ln.font === "string") el.font = ln.font;
    if (typeof ln.anim === "string") el.anim = ln.anim;
    if (typeof ln.x === "number") el.x = ln.x;
    if (typeof ln.y === "number") el.y = ln.y;
    if (typeof ln.fontSize === "number") el.fontSize = ln.fontSize;
    if (typeof ln.rotation === "number") el.rotation = ln.rotation;
  }

  // Audio defaults
  const audioCfg = audio || {
    sfxEnabled: true,
    padEnabled: true,
    sfxVolume: 0.7,
    padVolume: 0.4,
  };

  // Write config
  const compositionSrc = `// AUTO-GENERATED by api/server.mjs
import type { GeneratedConfig } from "./_types";

export const GENERATED_CONFIG: GeneratedConfig = ${JSON.stringify(
    { elements: preset.elements, audio: audioCfg },
    null,
    2
  )};
`;
  mkdirSync(dirname(TMP_CONFIG), { recursive: true });
  writeFileSync(TMP_CONFIG, compositionSrc);

  // Output filename
  const safeName = (name || "broll").replace(/[^a-zA-Z0-9-_]/g, "-");
  const outputArg = `out/${safeName}-${Date.now()}.mp4`;

  // Spawn render
  const isWin = process.platform === "win32";
  const remotionBin = isWin
    ? "node_modules\\.bin\\remotion.cmd"
    : "node_modules/.bin/remotion";

  const proc = spawn(
    remotionBin,
    ["render", "src/index.ts", "Broll", outputArg, "--concurrency", "1"],
    { cwd: ROOT, shell: isWin }
  );

  let stderr = "";
  proc.stderr.on("data", (d) => { stderr += d.toString(); });
  proc.stdout.on("data", () => {});

  proc.on("close", (code) => {
    if (code === 0) {
      const filename = outputArg.replace(/^out\//, "");
      res.json({ ok: true, url: `/out/${filename}` });
    } else {
      res.status(500).json({ error: "render failed", code, stderr });
    }
  });
});

// ─── GET /presets ───
app.get("/presets", async (req, res) => {
  const { readdirSync, readFileSync } = await import("node:fs");
  const files = readdirSync(PRESETS_DIR).filter((f) => f.endsWith(".json"));
  const presets = files.map((f) => {
    const p = JSON.parse(readFileSync(join(PRESETS_DIR, f), "utf8"));
    return {
      id: f.replace(".json", ""),
      name: p.name,
      description: p.description,
      elements: p.elements.map((e, i) => ({
        index: i,
        text: e.text,
        font: e.font,
        anim: e.anim,
        x: e.x,
        y: e.y,
        fontSize: e.fontSize,
        rotation: e.rotation,
      })),
    };
  });
  res.json({ presets });
});

// ─── GET /fonts ───
app.get("/fonts", (req, res) => {
  res.json({
    fonts: [
      { id: "display", label: "Plus Jakarta Sans (Bold sans)" },
      { id: "displayItalic", label: "Plus Jakarta Sans Italic" },
      { id: "sans", label: "Inter (Clean sans)" },
      { id: "classic", label: "Instrument Serif (Italic)" },
      { id: "mono", label: "JetBrains Mono" },
      { id: "script", label: "Great Vibes (Calligraphy)" },
      { id: "playfair", label: "Playfair Display Italic" },
    ],
    anims: [
      { id: "fade", label: "Fade in" },
      { id: "slideUp", label: "Slide up" },
      { id: "slideLeft", label: "Slide from right" },
      { id: "slideRight", label: "Slide from left" },
      { id: "scaleIn", label: "Scale in" },
      { id: "wordPop", label: "Word pop" },
      { id: "reveal", label: "Reveal (slow, for hero)" },
    ],
  });
});

const PORT = process.env.PORT || 3001;
app.listen(PORT, "127.0.0.1", () => {
  console.log(`🎬 Broll API running at http://127.0.0.1:${PORT}`);
});
